### PR TITLE
MQTTClient subscribe() now supports member functions

### PR DESCRIPTION
**Pull request by freedreamer82**
added a way to attach a member function in mqttclient subscribe

### CODE REVIEW

**Comment by icraggs** [comment]
Thanks for the PR.  I'd rather find a way of avoiding code duplication, so I've added an alternative solution in the following commit:

https://github.com/eclipse/paho.mqtt.embedded-c/commit/0690ccae833b09527f38efdf9f1b14aea54431aa

This also includes a sample and a test - I think it does what you need.

**Comment by freedreamer82** [comment]
I see code duplication issue, was my concern as well but I do not like very in your implementation the method setDefaultHandler. BTW it looks ok, thanks.

**Comment by icraggs** [comment]
@freedreamer82 I'm not sure I understand.  setDefaultHandler and the subscribe callbacks are alternatives.   It is not necessary to use the default handler, but that approach is more similar to other libraries I have written.

**Comment by freedreamer82** [comment]
I got now: My fault. I did not understand . Seems ok , I'm closing it.

**Pull request closed without merging**
