### PR TITLE
Expose FP<> message handler interface to API consumers

### PR DESCRIPTION
**Pull request by brimston3**
Signed-off-by: Andrew Domaszek <brimston3@hg0.us>

### CODE REVIEW

**Comment by brimston3** [comment]
Example use case is having two different C++ objects subscribed to different topics fed from 1 instance of the MQTTClient. By creating and attaching themselves to an FP<void, MQTT::MessageData&> object and passing it to subscribe(), they can both get callbacks without having to use a separate dispatch mechanism to figure out who owns what.

eg:
```
class C1 { void mRcv(MQTT::MessageData& msg) {} };
class C2 { void mRcv(MQTT::MessageData& msg) {} };
int main() {
  MQTTClient c;
  C1 c1;
  C2 c2;
  decltype(c)::MessageHandlerType fp1,fp2;
  /* ...connection instantiation omitted... */
  fp1.attach(&c1, &C1::mRcv);
  c.subscribe("test1", MQTT::QOS2, fp1);
  fp2.attach(&c2, &C2::mRcv);
  c.subscribe("test2", MQTT::QOS2, fp2);
  /* while (1) c.yield(); // or something more appropriate */
}
```

I exposed FP<> this way because it's a cheap way to get context-based function calls in this client without resorting to handling MQTTPacket myself via MQTTPacket_readnb(), which is what I was doing before. The object dispatch functionality is already present in FP<>, just unused by MQTTClient.

**Comment by denravonska** [comment]
An updates on when this will be merged? It also closes #120.

**Comment by icraggs** [comment]
Hello there.  Sorry it's taken so long for me to look at this.   If you want me to merge this in directly, you will have to sign the Eclipse Contributor Agreement (https://www.eclipse.org/legal/ECA.php) and ensure that the commits are signed off correctly.    These are the messages in the IP validation for the PR:

"The following users do not have valid ECAs. Please see this page for details, or to sign a ECA.
maciejt.nowak@gmail.com

The following users have invalid Signed-off-by footers. Please use the Signed-Off-By (git commit -s) mechanism to confirm the origin of the submission. The identity in the Signed-off-By must match the Author or the Committer.
noreply@github.com"

**Comment by brimston3** [comment]
Superseded by https://github.com/eclipse/paho.mqtt.embedded-c/commit/0690ccae833b09527f38efdf9f1b14aea54431aa #120

**Pull request closed without merging**
