### PR TITLE
fix load data instruction for cortex-m0 device

### PR DESCRIPTION
**Pull request by ATmega8**
Signed-off-by: ATmega8 <liuyang.2014@foxmail.com>

### CODE REVIEW

**Comment by scaprile** [comment]
Are you actually getting a warning ? It's been a long ago, but I compiled for a Cortex-M3 without a hassle.
What you suggest would work as casting to char would:
`writeChar(&ptr, (char)requestedQoSs[i]);`
which is a bit clearer, since the function definition is
`void writeChar(unsigned char** pptr, char c)`

**Comment by ATmega8** [comment]
@scaprile I get a **HardFault**. I read the disassembly code，the difference is

before
   `0x080027c6 <+106>:	bl	0x800257c <writeMQTTString>`
  `0x080027ca <+110>:	ldr	r2, [sp, #48]	; 0x30`
  ` 0x080027cc <+112>:	lsls	r3, r6, #2`
   `0x080027ce <+114>:	ldr	r1, [r2, r3]               /* HardFault */`
   `0x080027d0 <+116>:	add	r0, sp, #12`
   `0x080027d2 <+118>:	uxtb	r1, r1`
  `0x080027d4 <+120>:	bl	0x8002512  <writeChar>`

now
   `0x080027c6 <+106>:	bl	0x800257c <writeMQTTString>`
   `0x080027ca <+110>:	ldr	r2, [sp, #48]	; 0x30`
   `0x080027cc <+112>:	lsls	r3, r6, #2`
` 0x080027ce <+114>:	ldrb	r1, [r2, r3] `
 ` 0x080027d0 <+116>:	add	r0, sp, #12`
  ` 0x080027d2 <+118>:	bl	0x8002512 <writeChar>`


`
writeChar(&ptr, (char)requestedQoSs[i]);
`
This code not work, the disassemble code same to before.

`writeChar(&ptr, *(char*)(requestedQoSs+i));`
This code can work.

My Chip is STM32F051R8, compiler is arm-none-eabi-gcc 7.1.0

**Comment by scaprile** [comment]
Without the actual register values I can only guess, but I think you are having an alignment issue... What is the value of R2 ?
The M0 can not read unaligned integers, and requestedQoSs is an array of integers and so it must be word aligned (lay on an address which is a multiple of 4, bits 0 and 1 =0).
How are you constructing your QoS array and passing that value ? Are you having a warning you are ignoring in other function ?
My guess is that your casting is covering other issue you are ignoring in your code. requestedQoSs is an integer and the code should read an integer and eventually be casted to a char before being passed to the function being called, the mod you did causes it to read a char (a byte), so the only reason I see on an M0 for a HardFault exception is an alignment error.

**Comment by ATmega8** [comment]
you are right. QoS value in register,not in memory.I allocate memory to QoS value, then, it's can work.

**Pull request closed without merging**
